# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.




class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """

        list_s = []
        list_t = []

        for i in range(len(s)):
            list_s.append(s[i])

        for j in range(len(t)):
            list_t.append(t[j])

        for k in list_s:
            if k in list_t:
                list_t.remove(k)

        for p in list_t:
            return p